<?php

namespace Bluerock\Sellsy\Entities;

use Bluerock\Sellsy\Entities\Entity;

/**
 * The Subscription Entity.
 *
 * @package bluerock/sellsy-client
 * @author Ulysse <umetra@mc-media.com>
 * @version 1.2.1
 * @access public
 */
class Subscription extends Entity
{
    /**
     * Id of the subscription
     */
    public ?int $id;

    /**
     * Created date
     */
    public ?string $created;

    /**
     * Document to use as a template for subscription payment installments
     */
    public ?array $model;

    /**
     * Document to use as a template for subscription payment installments
     */
    public ?array $related;

    /**
     * Email sending configuration
     */
    public ?Sending $sending;

    /**
     * Source of payment preferences
     * Can be 'model', 'related'
     */
    public ?string $preferences_source;

    /**
     * <READONLY> Client owner from Sellsy.
     */
    public ?array $owner;

    /**
     * Conditions to generate subscription payment installments
     */
    public ?Conditions $conditions;

    /**
     * Id of the billing address
     */
    public ?int $billing_address;

    /**
     * Id of the shipping address
     */
    public ?int $shipping_address;

    /**
     * Order reference
     * <= 100 characters
     */
    public ?string $order_reference;

    /**
     * Update prices according to the products or services in the catalog
     * Default: false
     */
    public ?bool $has_updated_catalog_prices;

    /**
     * Take into account catalog promotions
     * Default: false
     */
    public ?bool $has_catalog_promotions;

    /**
     * Display the next recurrence date on the invoice
     * Default: false
     */
    public ?bool $has_display_of_next_deadline;

    /**
     * Display service dates on the invoice
     * Default: false
     */
    public ?bool $has_service_dates;

    /**
     * Service dates on the invoice
     * Prerequisite: has_service_dates should be true
     */
    public ?ServiceDates $service_dates;

    /**
     * Enable stock impact on new invoices generated by subscription
     * Prerequisite: The Stock module must be enabled and configured on your account to use this option
     * Default: false
     */
    public ?bool $has_impact_on_stock;

    /**
     * Specify the warehouse stock to be impacted once the invoice is generated
     * Prerequisite: has_impact_on_stock should be true
     * Prerequisite: The Stock module must be enabled and configured on your account to use this option
     * If specified to null, the default warehouse defined in the Stock module preferences will be used
     */
    public ?int $warehouse_id;

    /** 
     * Enable automatic payment by direct debit on new invoices generated by subscription
     * Prerequisite: The Gocardless or Stripe module (according to the one enabled on the document model used) must be enabled and configured on your account to use this option
     */
    public ?PaymentSettings $payment_settings;

    /**
     * Currency code of the invoice
     */
    public ?string $currency;

    /**
     * First payment date
     */
    public ?array $first_payment_installment_date;

    /**
     * Next payment date. If the value is null, the subscription is end.
     */
    public ?array $next_payment_installment_date;

    /**
     * Amounts of subscription
     */
    public ?Amounts $amounts;

    /**
     * Total number of invoices
     */
    public ?int $invoices_total_count;

    /**
     * Number of invoices generated
     */
    public ?int $invoices_generated_count;

    /**
     * Number of remaining invoices
     */
    public ?int $invoices_remaining_count;
}
